### ISSUE TITLE
Configuration for default values

### ISSUE THREAD

**Issue by liuggio** [liuggio/money#11]
One of @andrewtimberlake ideas is to create Money.new/1 with a default currency setting in config.
That would simplify things a great deal for projects that only use a single currency.
I only use Money.zar(100_00) because I don’t want to type Money.new(100_00, :ZAR) everywhere. If I could configure the default currency, then the convenience method becomes less important.
With Money.Helpers, you could do import Money.Helpers, only: [usd: 1] and then do usd(100_00) everywhere.

another feature would be adding:

`:separator` character between the whole and fraction amounts https://github.com/liuggio/money/blob/master/lib/money.ex#L338 
`:delimiter` character between each thousands place https://github.com/liuggio/money/blob/master/lib/money.ex#L340

**Comment by andrewtimberlake** [comment]
I agree. Do you know if Elixir has built-in i18n support that we can get number delimiters from?

**Comment by liuggio** [comment]
I never heard about it...
