### ISSUE TITLE
Infrastructure: Ecto Type

### ISSUE THREAD

**Issue by liuggio** [liuggio/money#12]
Would be great to add the Ecto behavior...

Adding value:
Designing applications with persistence ignorance is a good practice and delegate the Ecto type to the infrastructure layer would be a good practice...

**Comment by andrewtimberlake** [comment]
I’m thinking of two types.
A simple type that expects an integer in the database as the "cents" and uses the default currency discussed in #11 
Another type could be backed by a JSONB map in the database as `{amount: 100, currency: "USD"}` to allow for multi-currency support.

**Comment by liuggio** [comment]
closed by #17
