### ISSUE TITLE
The move to 1.0

### ISSUE THREAD

**Issue by andrewtimberlake** [liuggio/money#20]
I’m mostly happy with where things are.
What do you think we need to tackle before releasing 1.0?

- [x] #9 Multiply or Divide Money with Money
- [x] Update README
- [x] Remove config.exs

Anything else?

**Comment by liuggio** [comment]
The must for me is spend 1 minute and see if the API seems ok, because the stable release means not touching the api

**Comment by liuggio** [comment]
you made a great job, I don't have any other needs, except publish the docs :)

**Comment by liuggio** [comment]
maybe modify the https://github.com/liuggio/money/blob/master/config/config.exs  template?

**Comment by liuggio** [comment]
@andrewtimberlake hurray

**Comment by liuggio** [comment]
@andrewtimberlake ready to go stable?

**Comment by andrewtimberlake** [comment]
@liuggio Sorry, I was on holiday with my family.
Yup, I’m ready. I’ll do that today.

**Comment by andrewtimberlake** [comment]
1.0.0 released!
