### ISSUE TITLE
Amount gets multiplied by 100 when amount is parsed from a string

### ISSUE THREAD

**Issue by nicohvi** [liuggio/money#31]
Hi again!

I've run into a strange error. I have a `Purchase` Ecto model, which has the following schema:
```elixir
schema "purchases" do
  field :amount, Money.Ecto.Type

  timestamps
end
```

Adding an amount when the argument is an integer works fine:

```elixir
Purchase.changeset(%Purchase{}, %{amount: 50})
# Ecto.Changeset<changes: %{amount: %Money{amount: 50, currency: :NOK}>
```

*But*, when I pass in params as strings (which would be the case when an HTML form is posted) something weird happens.

```elixir
params = %{"amount" => "50"}
Purchase.changeset(%Purchase{}, params)
# Ecto.Changeset<changes: %{amount: %Money{amount: 5000, currency: :NOK}>
```

Any idea as to why this might happen?

**Comment by andrewtimberlake** [comment]
That’s intended.
The Ecto Type uses parse because users are likely to be typing in values such as "50" to represent $50 or "50.25" to represent $50.25.

**Comment by liuggio** [comment]
I think we should force type to be consistent with our money type what do you think?

**Comment by nicohvi** [comment]
Okay, thanks for the replies guys.

@andrewtimberlake does this mean that if I want to say 50 NOK (which is a currency that doesn't really utilise the concepts of 1/100th/cents anymore) then I'd have to divide it by 100 whenever I select it from the database, but not when storing it?

**Comment by andrewtimberlake** [comment]
@nicohvi That is an interesting situation.
I see from the Wikipedia article that the subunit øre is only used electronically.
If I understand the situation correctly, you should still not have a problem.
100 kr is still 10000 øre
To create 100 kr, you would do `Money.new(100_00, :NOK)`
Assuming your default currency is set to NOK,
- A value entered on a web form would be "100"
- this would be processed as `Money.parse("100")` which would result in `%Money{amount: 100_00, currency: :NOK}`

If I have misunderstood any of this, please let me know.

**Comment by nicohvi** [comment]
That's a very good point, @andrewtimberlake 👍 

The Øre has been out of use so long that I didn't even consider it, but it's a good point. I'll just have to keep that in mind in future then - thank you very much for your reply, and for the great library :-)
