### ISSUE TITLE
Supports for ExAdmin

### ISSUE THREAD

**Issue by Fs02** [liuggio/money#35]
Is there any plan to support ex_admin?
I've tried to give some support to make money work with ex_admin in my [fork](https://github.com/Fs02/money)
What I've done currently is only implementing ExAdmin.Render, but for the form, we still need to explicitly specify string as the type(this where I hit the walls).

**Comment by andrewtimberlake** [comment]
@Fs02 No there is no plan to support ExAdmin.
We have added support for Ecto and Phoenix because they are major libraries used by many in the community.
I suggest implementing the ExAdmin protocols for Money directly in your project.
This is what I do for things like JSON encoding.
