### ISSUE TITLE
protocol Phoenix.HTML.Safe not implemented

### ISSUE THREAD

**Issue by Harry27PL** [liuggio/money#37]
In docs:

> If you are using Phoenix, you can include money objects directly into your output and they will be correctly escaped.
`<%= Money.new(12345,67, :GBP) %>`

but it gives an error
> undefined function Money.new/3

I removed a comma from the number
`<%= Money.new(1234567, :GBP) %>`

it gives another error:
> protocol Phoenix.HTML.Safe not implemented for %Money{amount: 1234567, currency: :GBP}

**Comment by andrewtimberlake** [comment]
@Harry27PL Sorry, the Phoenix protocol was implemented in `master`
I have just published version 1.1.0 which has the protocol implemented.
