### ISSUE TITLE
Support for parsing negative values

### ISSUE THREAD

**Issue by iacobson** [liuggio/money#38]
Trying to run 
`Money.parse("-3.4")` will result in positive value:
`{:ok, %Money{amount: 340, currency: :GBP}}`
is it possible to generate negative ?
I know this can be achieved with `Money.new(-....)` but my input is float so need to use the `parse`

**Comment by iacobson** [comment]
That was quick ! Thanks so much !

**Comment by andrewtimberlake** [comment]
No problem. I also pushed release 1.1.0 with some other updates
