### ISSUE TITLE
Move currency shortcuts to a separate module

### ISSUE THREAD

**Issue by andrewtimberlake** [liuggio/money#4]
When running documentation, the shortcut methods for each currency, `Money.usd/1`, `Money.gbp/1` etc clutter up the namespace.
I think we should move those to another module. Perhaps `Money.Helpers.usd`
What do you think?

**Comment by liuggio** [comment]
@andrewtimberlake the shortcuts are factory methods in order to simplify the API of this lib and moving to Helpers wouldn't be so read-able, but i do get your concerns... do you see other solutions?

**Comment by andrewtimberlake** [comment]
One of my ideas is to create `Money.new/1` with a default currency setting in config.
That would simplify things a great deal for projects that only use a single currency.
I only use `Money.zar(100_00)` because I don’t want to type `Money.new(100_00, :ZAR)` everywhere. If I could configure the default currency, then the convenience method becomes less important.
With `Money.Helpers`, you could do `import Money.Helpers, only: [usd: 1]` and then do `usd(100_00)` everywhere.

**Comment by liuggio** [comment]
I'm ok with it!

**Comment by andrewtimberlake** [comment]
It’s working out to be `Money.Currency` which is quite nice. It puts all currency specific functionality into its own module.
See #8

**Comment by liuggio** [comment]
fixed with https://github.com/liuggio/money/pull/8
