### ISSUE TITLE
to_string for negative values

### ISSUE THREAD

**Issue by iacobson** [liuggio/money#41]
If I create a negative value:
`m = Money.new(-20000)`
%Money{amount: -200, currency: :GBP}

and I try to convert it to string
`Money.to_string(m)`
I get a wrong format like
**"-,200.00"**

This happens when I try to convert values of hundreds such as:
200.00
200000.00
etc.

**Comment by iacobson** [comment]
Thanks again for the quick resolution.
However I have updated the Money:
`mix deps.update money`

It shows `:money, "1.1.1"` in my mix.lock

But behaves the same both in my project as in console.
Is there anything else I should do?
Thanks

**Comment by andrewtimberlake** [comment]
Oh the shame :-(
To fix a bug which is not fixed. I’m reopening this and I’ll see what’s wrong.

**Comment by andrewtimberlake** [comment]
Sorry, I did something wrong when releasing 1.1.1
I have released 1.1.2 and tested that it works.

**Comment by iacobson** [comment]
Works perfectly ! Thanks !
