### ISSUE TITLE
Change Money.new/2 with string

### ISSUE THREAD

**Issue by andrewtimberlake** [liuggio/money#5]
I don’t think `Money.new/2` should work as it does,
```elixir
iex> Money.new("1000", :USD)
%Money{amount: 1000, currency: :USD}
```

Instead you should be able to do (this is important for working with form input)
```elixir
iex> Money.new("$10.00", :USD)
%Money{amount: 1000, currency: :USD)
# This means that
iex> Money.new("10", :USD)
%Money{amount: 1000, currency: :USD}
```

We probably still need the currency atom because a number of currencies share symbols. $ is for USD, AUD, etc
Another option is to have `Money.new/2` only take the amount as an integer and introduce `Money.parse/2` to handle strings.

**Comment by liuggio** [comment]
@andrewtimberlake 

This implementation:       `Money.new(1000, :USD)`
would be different from:  `Money.new("1000", :USD)`
and would be equal to:  `Money.new("10", :USD)`

kind of weird, 

but the parse/2 idea is **great**!!

**Comment by andrewtimberlake** [comment]
It is weird unless you consider that the string representation of `Money` is "$10.00"
This way `Money.new(1000, :USD) |> Money.to_string |> Money.new(:USD)` makes more sense.
Think about how you’d work with HTML forms.
You display the amount in a text field and then need to convert it back to `Money` from it’s text representation.
