### ISSUE TITLE
Possible problem when parsing floats

### ISSUE THREAD

**Issue by optikfluffel** [liuggio/money#50]
Since [`parse(float, currency, _opts)`](https://github.com/liuggio/money/blob/master/lib/money.ex#L122-L124) uses `* 100` hardcoded, there's unexpected behaviour when using currencies like [TND](https://en.wikipedia.org/wiki/Tunisian_dinar), where the conversion to the smaller unit (milim or millimes) is `* 1000`.
I haven't looked into other ones and just stumbled upon this while reading the code, but I have the feeling that there could be more currencies with that kind of problem.

**Comment by andrewtimberlake** [comment]
There are a few currencies that don’t follow the "standard" pattern of subdivision into 100 subunits.
I don’t have the time right now to work on those variations as I don’t work with those currencies.
Pull requests are welcome.

**Comment by jordi-adame** [comment]
@optikfluffel this is fixed today @ master https://github.com/liuggio/money/pull/61

**Comment by Nitrino** [comment]
Sorry, in #60.
I think we can close the fixed issues.
