### ISSUE TITLE
Make precision customizable

### ISSUE THREAD

**Issue by Secretmapper** [liuggio/money#67]
It should be possible to edit the default precision and pass precision as an option when parsing/converting to string.

My use case for this is that I'm working with cryptocurrencies, and precision for my use case needs to be quite high (i.e. right now, 1 XRP === $0.320442)

Related: https://github.com/liuggio/money/pull/62

I'll be able to work on the PR above to customize it a bit more for my use case (making to_string add precision as an opt), but would like to know what the core team thinks about it

**Comment by Nitrino** [comment]
I think this should look like the infinite_precision flag. 
In this case, integer storage type will not work. It is necessary to use decimal, JSON or composite type.

**Comment by Secretmapper** [comment]
After thinking about it, I just realized that there is somewhat support for this with `exponent`, i.e. USD has exponent 2 so it will always show 2 decimal places.

If there is a way we can somehow pass exponent when calling `to_string`, that would solve this specific use case.

**Comment by Nitrino** [comment]
I think this should be solved with the help of currency customization. Related with #88 
If you still need it or have ideas, post here or open a new issue
