### ISSUE TITLE
Can I incorporate floats

### ISSUE THREAD

**Issue by andrewtimberlake** [liuggio/money#7]
I want to be able to work with floats, any objection to this:
```
iex> Money.new(100.55, :USD) |> Money.add(10.12)
%Money{amount: 11067, currency: :USD}
```

**Comment by liuggio** [comment]
:+1:

**Comment by liuggio** [comment]
this is dangerous the dev must be sure that the value is Integer or Float  :fearful:

**Comment by andrewtimberlake** [comment]
That is a good point.
One way to mitigate that is to remove float support in `new` but still allow it in `add`, `subtract`, `multiply`, and `divide`?

**Comment by liuggio** [comment]
yes, I still think that `parse` is a good idea.

**Comment by andrewtimberlake** [comment]
Can I limit `new` to only accept integers and then provide parse for String and float support?

**Comment by liuggio** [comment]
super :+1:

**Comment by liuggio** [comment]
implemented by https://github.com/liuggio/money/pull/15
