### ISSUE TITLE
Implement Enumerable for %Money{}

### ISSUE THREAD

**Issue by Sitch** [liuggio/money#77]
Currently get an error if i try to enumerate over a money object (easy fix on my side, but would be good to be part of the lib)

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for %Money{amount: 0, currency: :USD}
```

**Comment by andrewtimberlake** [comment]
How are you trying to enumerate the Money object? Could you give your expected surrounding code?

**Comment by Sitch** [comment]
Usecase was with the ex_machina library for their `string_params_for/?` call which tries to enumerate `%Money{}`

**Comment by andrewtimberlake** [comment]
ex_machina is trying to convert a Money into a string representation that can be used in a form right? `%Money{amount: 10000, currency: :USD}` could be "$100.00" or "100" and both would work as form input.
A `Money` is a value, not a collection so I don’t think it makes sense to implement enumerable.
Perhaps you could discuss with Thoughtbot that they implement a protocol for handling values like this. I use protocols to handle the conversion of `Money` values in JSON, CSV, etc.
