### ISSUE TITLE
The latest release on Hex doesn't include recent features

### ISSUE THREAD

**Issue by GregMefford** [liuggio/money#78]
It would be really great if we could get an updated version pushed to Hex. Specifically, I want to be able to use the Ecto type in an embedded schema stored in a jsonb column in Postgresql, but the version on Hex doesn't know how to cast `%{amount: 1000, currency: "USD"}` to `%Money{}`.

In the meantime, am just pointing to the latest commit ref using a `github:` dependency in my `mix.exs`, which seems to be working well.

**Comment by Nitrino** [comment]
@liuggio can you please update hex package?

**Comment by ericmj** [comment]
Since this package is not active on Hex and the owner is not responding here you can message support@hex.pm to start the process to take over the package. I would recommend one (or more) of the core devs that have push access to the repository do it.

**Comment by Nitrino** [comment]
@ericmj Thank you for your attention to the community.

I have a push access for this repository.
I wrote a letter to both owners (@liuggio and @andrewtimberlake ) of this hex.
I will wait for a response within 2-3 days, after which I plan to contact support for hex.pm.
After gaining access to the hex, I will try to help the community as much as I can.

**Comment by ericmj** [comment]
Hi @Nitrino. I actually already started the take over process, which means I will get ownership of the package within 30 days unless the owners respond. If you would like to maintain the package I would be happy to hand over the ownership to you.

**Comment by Nitrino** [comment]
Hi @ericmj. @liuggio answered on my letter and he said that gives access as will be at the computer.
I think it will be faster than the take over process.

**Comment by ericmj** [comment]
@Nitrino It seems you have access now. Can you publish the 1.2.2 tag?

**Comment by Nitrino** [comment]
Hi @ericmj. Yes, I got access.
I published version [1.3.0](https://hex.pm/packages/money/1.3.0) with all current changes and support for the latest elixir versions.

Thanks for the help. If you want, I can now give you access to this package.

**Comment by ericmj** [comment]
Thank you! 💜 

No need to give me access.
