### ISSUE TITLE
Where currency rates come from?

### ISSUE THREAD

**Issue by jomei** [liuggio/money#88]
Hello!

I read your docs and didn't realize what source of currency rates and what should I do to retrieve that rates.
Am I missed it?

**Comment by Nitrino** [comment]
@GregMefford is right, there is currently no currency exchange functionality.
But it is planned in the next versions.

**Comment by Nitrino** [comment]
I think this should be solved with the help of currency customization. Related with #88
If you still need it or have ideas, post here or open a new issue.

**Comment by Nitrino** [comment]
Duplicate #54
